// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC03aPNrETu_W6T7As8sjEmB1uDBkx2TWI',
    appId: '1:100722054728:web:19d8a341bbef1d8f9c2a7d',
    messagingSenderId: '100722054728',
    projectId: 'santos-advmblprog-10702',
    authDomain: 'santos-advmblprog-10702.firebaseapp.com',
    storageBucket: 'santos-advmblprog-10702.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQwSUf2xVgJz9rDJcMLqxasyAzX1aGaxE',
    appId: '1:100722054728:android:c58360a1849c07a09c2a7d',
    messagingSenderId: '100722054728',
    projectId: 'santos-advmblprog-10702',
    storageBucket: 'santos-advmblprog-10702.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPD3mYB4xbvAp-1w3mi4z0KLvOVFUcREw',
    appId: '1:100722054728:ios:d76fd5d4ca6b18b79c2a7d',
    messagingSenderId: '100722054728',
    projectId: 'santos-advmblprog-10702',
    storageBucket: 'santos-advmblprog-10702.firebasestorage.app',
    iosBundleId: 'com.example.santosAdvmobprog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPD3mYB4xbvAp-1w3mi4z0KLvOVFUcREw',
    appId: '1:100722054728:ios:d76fd5d4ca6b18b79c2a7d',
    messagingSenderId: '100722054728',
    projectId: 'santos-advmblprog-10702',
    storageBucket: 'santos-advmblprog-10702.firebasestorage.app',
    iosBundleId: 'com.example.santosAdvmobprog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC03aPNrETu_W6T7As8sjEmB1uDBkx2TWI',
    appId: '1:100722054728:web:02a3405ed5dd4ef89c2a7d',
    messagingSenderId: '100722054728',
    projectId: 'santos-advmblprog-10702',
    authDomain: 'santos-advmblprog-10702.firebaseapp.com',
    storageBucket: 'santos-advmblprog-10702.firebasestorage.app',
  );
}
